name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    name: "Build on Ubuntu"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: sudo apt update

      - name: Install meson
        run: sudo apt install meson
        
      - name: Install dependencies
        run: sudo apt install libsfml-dev libboost-all-dev
        
      - name: Configure the project with meson
        run: meson build
        
      - name: Compile
        run: ninja -vC build

  build-windows:
    name: "Build on Windows"
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Path
        run: echo "C:\Users\runneradmin\AppData\Roaming\Python\Python37\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install meson
        run: python -m pip install --user meson

      - name: Install ninja
        run: choco install ninja

      - name: Install sfml
        run: |
            $url = "https://www.sfml-dev.org/files/SFML-2.5.1-windows-gcc-7.3.0-mingw-64-bit.zip"
            $archive = "c:\sfml.zip"
            $dir = "c:\sfml"

            Invoke-WebRequest -Uri $url -OutFile $archive
            Expand-Archive -LiteralPath $output -DestinationPath $dir

      - run: set BOOST_ROOT=BOOST_ROOT_1_72_0

      - name: Setup the project with meson
        run: meson build

      - name: Compile
        run: ninja -vC build    
